#!/bin/bash
sudo -u ec2-user -i << 'EOF'

# This will affect only the pytorch_p38 Jupyter kernel
source activate pytorch_p38 

pip install -U setuptools wheel numpy scipy
pip install autogluon==0.5.2
pip install mxnet-cu110==1.9.1

conda deactivate

EOF
